# Generated by Django 5.2.2 on 2025-10-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='eixo',
            field=models.CharField(blank=True, choices=[('SAUDE', 'Eixo da Saúde'), ('GESTAO', 'Eixo de Gestão')], help_text='Eixo ao qual o servidor pertence.', max_length=10, null=True),
        ),
    ]
