# Generated by Django 5.2.2 on 2025-10-21 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_eixo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorMateriaAnoCursoModalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_modulo', models.CharField(choices=[('1º ANO', '1º ANO'), ('2º ANO', '2º ANO'), ('3º ANO', '3º ANO'), ('I MÓDULO', 'I MÓDULO'), ('II MÓDULO', 'II MÓDULO'), ('III MÓDULO', 'III MÓDULO'), ('IV MÓDULO', 'IV MÓDULO'), ('V MÓDULO', 'V MÓDULO'), ('VI MÓDULO', 'VI MÓDULO')], max_length=20)),
                ('modalidade', models.CharField(choices=[('EPI', 'EPI (Diurno)'), ('PROEJA', 'PROEJA (Noturno)'), ('SUBSEQUENTE', 'Subsequente (Noturno)')], max_length=20)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
                ('professor', models.ForeignKey(limit_choices_to={'tipo': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo de Professor',
                'verbose_name_plural': 'Vínculos de Professores',
                'unique_together': {('professor', 'materia', 'curso', 'ano_modulo', 'modalidade')},
            },
        ),
        migrations.DeleteModel(
            name='ProfessorMateriaTurma',
        ),
    ]
