# Generated by Django 5.2.2 on 2025-10-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_professormateriaanocursomodalidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professormateriaanocursomodalidade',
            name='modalidade',
            field=models.CharField(choices=[('EPI', 'EPI'), ('PROEJA', 'PROEJA'), ('SUBSEQUENTE', 'Subsequente')], max_length=20),
        ),
    ]
