# Generated by Django 5.2.2 on 2025-10-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_professormateriaanocursomodalidade_modalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoestagio',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho (Pelo Aluno)'), ('CONCLUIDO_ALUNO', 'Concluído (Pelo Aluno)'), ('REPROVADO', 'Reprovado (Pendente de Correção)')], default='RASCUNHO', max_length=30),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='status_geral',
            field=models.CharField(choices=[('RASCUNHO_ALUNO', 'Rascunho (Aluno preenchendo)'), ('AGUARDANDO_ORIENTADOR', 'Aguardando Análise do Prof. Orientador'), ('AGUARDANDO_SERVIDOR', 'Em Análise (Aguardando Servidor/Direção)'), ('APROVADO', 'Aprovado'), ('PENDENTE_CORRECAO', 'Pendente de Correções')], default='RASCUNHO_ALUNO', max_length=50),
        ),
    ]
