# Generated by Django 5.2.2 on 2025-10-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_documentoestagio_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Admin'), ('professor', 'Professor'), ('aluno', 'Aluno'), ('servidor', 'Servidor'), ('direcao', 'Direção')], default='admin', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentoestagio',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho (Pelo Aluno)'), ('AGUARDANDO_ASSINATURA_PROF', 'Aguardando Assinatura (Professor)'), ('AGUARDANDO_ASSINATURA_DIR', 'Aguardando Assinatura (Direção)'), ('CONCLUIDO', 'Concluído'), ('REPROVADO', 'Reprovado (Pendente de Correção)')], default='RASCUNHO', max_length=30),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='status_geral',
            field=models.CharField(choices=[('RASCUNHO_ALUNO', 'Rascunho (Aluno preenchendo)'), ('EM_ANDAMENTO', 'Em Andamento (Aguardando assinaturas)'), ('APROVADO', 'Aprovado (Todas assinaturas concluídas)'), ('PENDENTE_CORRECAO', 'Pendente de Correções')], default='RASCUNHO_ALUNO', max_length=50),
        ),
    ]
